spring.application.name=quickcontacts
server.port=8080

# DATABASE CONFIGURATION (SUPABASE POSTGRESQL)

# Port 6543 is used for connection pooling (best for Spring Boot)
spring.datasource.url=jdbc:postgresql://db.exeydhrvqpqcgbwoawpj.supabase.co:5432/postgres?prepareThreshold=0
# Replace [REF_ID] with your Supabase Project Reference ID
spring.datasource.username=postgres.exeydhrvqpqcgbwoawpj
# Replace [PASSWORD] with your actual Supabase Database Password
spring.datasource.password=Spring!2026$Db
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE SETTINGS

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# 'update' will automatically create/update tables in Supabase based on your Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GOOGLE OAUTH2 CLIENT CONFIGURATION

spring.security.oauth2.client.registration.google.client-id=257588802571-f985rdrsmabffqlpqba2nbenqg9kompu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=profile,email,https://www.googleapis.com/auth/contacts.readonly

# LOGGING & DEBUGGING

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

